# Generated by Django 6.0.3 on 2026-04-02 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "rate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("rate_type", models.CharField(db_index=True, max_length=255)),
                ("rate_value", models.DecimalField(decimal_places=6, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("effective_date", models.DateField(db_index=True)),
                ("ingestion_ts", models.DateTimeField(db_index=True)),
                ("sys_ingested_ts", models.DateTimeField(db_index=True)),
                (
                    "raw_response_id",
                    models.UUIDField(db_index=True, editable=False, unique=True),
                ),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("raw_data_snapshot", models.JSONField(null=True)),
            ],
            options={
                "db_table": "rates",
                "ordering": ["-effective_date", "-sys_ingested_ts"],
                "indexes": [
                    models.Index(
                        fields=[
                            "provider",
                            "rate_type",
                            "-effective_date",
                            "-sys_ingested_ts",
                        ],
                        name="provider_rate_lookup_idx",
                    )
                ],
            },
        ),
    ]
